### ISSUE TITLE
No source maps for dart-scss configured

### ISSUE THREAD

**Issue by mildred** [rails/cssbundling-rails#68] opened 2022-01-17 16:30 UTC
It would be great if cssbundling-rails could generate source maps.

For scss, the --no-source-map flag is in use, and if source maps are enabled, the source filename included in the map file is relative to the source directory, resulting in the browser not being able to find the source location. Not only that, but the scss source might not even be accessible from the client-side.

**Comment by jrochkind** [comment] 2022-08-25 21:25
I feel like I've been waiting many years for sourcemaps for SCSS in rails, back from when it was "coming soon" in sprockets years ago (still doesn't work, for me anyway, in latest sprockets 4). 

I naively assumed I was going to get this with the cssbundling-rails sass, since it was my impression that it was considered a standard feature in "ordinary JS sass", which we were using now... very surprised to find it is still not working!

Thanks to @thebravoman for seeing how far you could get it, and the diagnosis. I would be interesting in doing some work to send a PR if there was some indication it might get reviewed and possibly merged, but I share @thebravoman's questions, it's not clear to me what tool should be taking care of this, it does seem to be a bit of a leak in the css-bundling rails abstraction. 

But we need sourcemaps right? It's pretty crucial for debugging your CSS -- in my current sprockets use at least I hvae those old-style comments tellling me the original file and line a produced CSS line came from, without even that it's going to feel like a bit step backwards!

**Comment by jrochkind** [comment] 2022-08-25 21:36
I'm not sure my situation is exactly the same as what @thebravoman encountered/diagnosed. 

I am looking in development rather than prod (this is where I want sourcemaps myself). If I remove `--no-source-maps` to have the `sass` tool build a sourcemap... when chrome dev tools try to show source, the problem is that it can't find the original source file, I get it telling me:

    Could not load content for http://localhost:3001/stylesheets/my_local_css_file.scss (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

I think the source map file itself may be working okay, but the browser needs to access the original source file (not the aggregated application.css) in order to show it... and the URL the source map gives for that original source file doesn't work... but I'm not sure there if there is any URL that would, I'm not sure if the Rails app is willing to serve these original source files in (eg) `./app/assets/stylesheets` at all, in dev?

Going to try to compare to what happens with JS and esbuild via jsbundling-rails, not sure if sourcemaps are working there...

**Comment by danielnc** [comment] 2022-09-20 17:39
I am having a similar issue to what @thebravoman described, but on my `assets/build/application.css` I can only see `/*# sourceMappingURL=application.css.map */` at the end of the file, still no success and chrome renders the following error:

```
DevTools failed to load source map: Could not load content for http://myaccount.lvh.me:3000/assets/application.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by alessandro-fazzi** [comment] 2023-06-07 14:12
This is the configuration I use on several projects nowadays

```diff
diff --git a/config/environments/development.rb b/config/environments/development.rb
index 1fc05c36..c9b9f03f 100644
--- a/config/environments/development.rb
+++ b/config/environments/development.rb
@@ -58,7 +58,7 @@ Rails.application.configure do
   # Debug mode disables concatenation and preprocessing of assets.
   # This option may cause significant delays in view rendering with a large
   # number of complex assets.
-  config.assets.debug = true
+  config.assets.debug = false
 
   # Suppress logger output for asset requests.
   config.assets.quiet = true
diff --git a/package.json b/package.json
index dd695cb4..277808ec 100644
--- a/package.json
+++ b/package.json
@@ -36,7 +36,7 @@
     [redacted],
     [redacted],
     [redacted],
-    "build:css": "sass ./app/assets/stylesheets/application.scss ./app/assets/builds/application.css --load-path=node_modules"
+    "build:css": "sass ./app/assets/stylesheets/application.scss ./app/assets/builds/application.css --load-path=node_modules --embed-sources"
   },
   "packageManager": "yarn@3.3.0",
   "resolutions": {
```

**Comment by aaronjensen** [comment] 2023-06-18 18:07
If you're using Propshaft and dart-sass, https://github.com/rails/propshaft/pull/133 will need to be merged, but once it is, source maps work.

**Closed** 2024-01-21 19:40 UTC
